version: '3.4'

services:
  AirTrafficInfo_1:
    image: airtrafficinfo
    container_name: airtrafficinfo_1
    build:
      context: ./AirTrafficInfo
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8880:80"
  

#USA
  Airport_new_york:
    image: airport
    container_name: airport_new_york
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8801:80"
    command: --name="New York" --color=#0000FF --latitude=40.68 --longitude=-74.17
  Airport_miami:
    image: airport
    container_name: airport_miami
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8802:80"
    command: --name="Miami" --color=#0b40f4 --latitude=25.78 --longitude=-80.17
  Airport_los_angeles:
    image: airport
    container_name: airport_los_angeles
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8803:80"
    command: --name="Los Angeles" --color=#0a3bdb --latitude=33.93 --longitude=-118.4
  Airport_san_francisco:
    image: airport
    container_name: airport_san_francisco
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8804:80"
    command: --name="San Francisco" --color=#082eaa --latitude=37.78 --longitude=-122.41
    
  
#Europe
  Airport_london:
    image: airport
    container_name: airport_london
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8811:80"
    command: --name=London --color=#FF0000 --latitude=51.48 --longitude=-0.11
  Airport_sevilla:
    image: airport
    container_name: airport_sevilla
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8812:80"
    command: --name=Sevilla --color=#ff1a1a --latitude=37.37 --longitude=-5.98
  Airport_rome:
    image: airport
    container_name: airport_rome
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8813:80"
    command: --name=Rome --color=#ff1a1a --latitude=41.89 --longitude=12.5
  Airport_moscow:
    image: airport
    container_name: airport_moscow
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8814:80"
    command: --name=Moscow --color=#ff3333 --latitude=55.75 --longitude=37.63


#Asia    
  Airport_tokyo:
    image: airport
    container_name: airport_tokyo
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8821:80"
    command: --name=Tokyo --color=#ff00ff --latitude=35.67 --longitude=139.75
  Airport_kuala_lumpur:
    image: airport
    container_name: airport_kuala_lumpur
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8822:80"
    command: --name="Kuala Lumpur" --color=#1affff --latitude=3.13 --longitude=101.68


#Middle East
  Airport_cairo:
    image: airport
    container_name: airport_cairo
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8831:80"
    command: --name=Cairo --color=#ffff00 --latitude=29.9 --longitude=31.4
  Airport_dubai:
    image: airport
    container_name: airport_dubai
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8832:80"
    command: --name=Dubai --color=#ffff33 --latitude=25.3 --longitude=55.2


#Australia
  Airport_sydney:
    image: airport
    container_name: airport_sydney
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8841:80"
    command: --name=Sydney --color=#c61aff --latitude=-33.8 --longitude=151.2


#South America
  Airport_rio_de_janeiro:
    image: airport
    container_name: airport_rio_de_janeiro
    build:
      context: ./Airport
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8851:80"
    command: --name="Rio De Janeiro" --color=#40ff00 --latitude=-22.9 --longitude=-43.2


#Planes and Pilots
  Plane_1:
    image: plane
    container_name: plane_1
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8001:80"
    command: --name="Plane 1"
  Plane_2:
    image: plane
    container_name: plane_2
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8002:80"
    command: --name="Plane 2"
  Plane_3:
    image: plane
    container_name: plane_3
    build:
      context: ./Plane
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8003:80"
    command: --name="Plane 3"
